### ISSUE TITLE
Compile error on device UNO

### ISSUE THREAD

**Issue by lqforgithub** [WiserUFBA/ArduMideaWrapper#11]
libraries/MideaIRWrapper/MidearIR.cpp.o (symbol from plugin): In function `irparams':
(.text+0x0): multiple definition of `irparams'
sketch/basic_commands.ino.cpp.o (symbol from plugin):(.text+0x0): first defined here
libraries/MideaIRWrapper/MidearIR.cpp.o (symbol from plugin): In function `irparams':
(.text+0x0): multiple definition of `timerConfigForSend(unsigned char)'
sketch/basic_commands.ino.cpp.o (symbol from plugin):(.text+0x0): first defined here
libraries/MideaIRWrapper/MidearIR.cpp.o (symbol from plugin): In function `irparams':
(.text+0x0): multiple definition of `timerConfigForReceive()'
sketch/basic_commands.ino.cpp.o (symbol from plugin):(.text+0x0): first defined here
libraries/MideaIRWrapper/MidearIR.cpp.o (symbol from plugin): In function `irparams':
(.text+0x0): multiple definition of `setLEDFeedback(unsigned char, bool)'
sketch/basic_commands.ino.cpp.o (symbol from plugin):(.text+0x0): first defined here
libraries/MideaIRWrapper/MidearIR.cpp.o (symbol from plugin): In function `irparams':
(.text+0x0): multiple definition of `FeedbackLEDControl'
sketch/basic_commands.ino.cpp.o (symbol from plugin):(.text+0x0): first defined here
libraries/MideaIRWrapper/MidearIR.cpp.o (symbol from plugin): In function `irparams':
(.text+0x0): multiple definition of `enableLEDFeedback()'
sketch/basic_commands.ino.cpp.o (symbol from plugin):(.text+0x0): first defined here
libraries/MideaIRWrapper/MidearIR.cpp.o (symbol from plugin): In function `irparams':
(.text+0x0): multiple definition of `disableLEDFeedback()'
sketch/basic_commands.ino.cpp.o (symbol from plugin):(.text+0x0): first defined here
libraries/MideaIRWrapper/MidearIR.cpp.o (symbol from plugin): In function `irparams':
(.text+0x0): multiple definition of `setFeedbackLED(bool)'
sketch/basic_commands.ino.cpp.o (symbol from plugin):(.text+0x0): first defined here
libraries/MideaIRWrapper/MidearIR.cpp.o (symbol from plugin): In function `irparams':
(.text+0x0): multiple definition of `blink13(bool)'
sketch/basic_commands.ino.cpp.o (symbol from plugin):(.text+0x0): first defined here
libraries/MideaIRWrapper/MidearIR.cpp.o (symbol from plugin): In function `irparams':
(.text+0x0): multiple definition of `setBlinkPin(unsigned char)'
sketch/basic_commands.ino.cpp.o (symbol from plugin):(.text+0x0): first defined here
libraries/MideaIRWrapper/MidearIR.cpp.o (symbol from plugin): In function `irparams':
(.text+0x0): multiple definition of `IRrecv::setReceivePin(unsigned char)'
sketch/basic_commands.ino.cpp.o (symbol from plugin):(.text+0x0): first defined here
libraries/MideaIRWrapper/MidearIR.cpp.o (symbol from plugin): In function `irparams':
(.text+0x0): multiple definition of `IRrecv::IRrecv()'
sketch/basic_commands.ino.cpp.o (symbol from plugin):(.text+0x0): first defined here
libraries/MideaIRWrapper/MidearIR.cpp.o (symbol from plugin): In function `irparams':
(.text+0x0): multiple definition of `IRrecv::IRrecv()'
sketch/basic_commands.ino.cpp.o (symbol from plugin):(.text+0x0): first defined here
libraries/MideaIRWrapper/MidearIR.cpp.o (symbol from plugin): In function `irparams':
(.text+0x0): multiple definition of `IrReceiver'
sketch/basic_commands.ino.cpp.o (symbol from plugin):(.text+0x0): first defined here
libraries/MideaIRWrapper/MidearIR.cpp.o (symbol from plugin): In function `irparams':
(.text+0x0): multiple definition of `IRrecv::IRrecv(unsigned char)'
sketch/basic_commands.ino.cpp.o (symbol from plugin):(.text+0x0): first defined here
libraries/MideaIRWrapper/MidearIR.cpp.o (symbol from plugin): In function `irparams':
(.text+0x0): multiple definition of `IRrecv::IRrecv(unsigned char)'
sketch/basic_commands.ino.cpp.o (symbol from plugin):(.text+0x0): first defined here
libraries/MideaIRWrapper/MidearIR.cpp.o (symbol from plugin): In function `irparams':
(.text+0x0): multiple definition of `IRrecv::IRrecv(unsigned char, unsigned char)'
sketch/basic_commands.ino.cpp.o (symbol from plugin):(.text+0x0): first defined here
libraries/MideaIRWrapper/MidearIR.cpp.o (symbol from plugin): In function `irparams':
(.text+0x0): multiple definition of `IRrecv::IRrecv(unsigned char, unsigned char)'
sketch/basic_commands.ino.cpp.o (symbol from plugin):(.text+0x0): first defined here
libraries/MideaIRWrapper/MidearIR.cpp.o (symbol from plugin): In function `irparams':
(.text+0x0): multiple definition of `IRrecv::stop()'
sketch/basic_commands.ino.cpp.o (symbol from plugin):(.text+0x0): first defined here
libraries/MideaIRWrapper/MidearIR.cpp.o (symbol from plugin): In function `irparams':
(.text+0x0): multiple definition of `IRrecv::end()'
sketch/basic_commands.ino.cpp.o (symbol from plugin):(.text+0x0): first defined here
libraries/MideaIRWrapper/MidearIR.cpp.o (symbol from plugin): In function `irparams':
(.text+0x0): multiple definition of `IRrecv::disableIRIn()'
sketch/basic_commands.ino.cpp.o (symbol from plugin):(.text+0x0): first defined here
libraries/MideaIRWrapper/MidearIR.cpp.o (symbol from plugin): In function `irparams':
(.text+0x0): multiple definition of `IRrecv::isIdle()'
sketch/basic_commands.ino.cpp.o (symbol from plugin):(.text+0x0): first defined here
libraries/MideaIRWrapper/MidearIR.cpp.o (symbol from plugin): In function `irparams':
(.text+0x0): multiple definition of `IRrecv::resume()'
sketch/basic_commands.ino.cpp.o (symbol from plugin):(.text+0x0): first defined here
libraries/MideaIRWrapper/MidearIR.cpp.o (symbol from plugin): In function `irparams':
(.text+0x0): multiple definition of `IRrecv::enableIRIn()'
sketch/basic_commands.ino.cpp.o (symbol from plugin):(.text+0x0): first defined here
libraries/MideaIRWrapper/MidearIR.cpp.o (symbol from plugin): In function `irparams':
(.text+0x0): multiple definition of `IRrecv::begin(unsigned char, bool, unsigned char)'
sketch/basic_commands.ino.cpp.o (symbol from plugin):(.text+0x0): first defined here
libraries/MideaIRWrapper/MidearIR.cpp.o (symbol from plugin): In function `irparams':
(.text+0x0): multiple definition of `IRrecv::start()'
sketch/basic_commands.ino.cpp.o (symbol from plugin):(.text+0x0): first defined here
libraries/MideaIRWrapper/MidearIR.cpp.o (symbol from plugin): In function `irparams':
(.text+0x0): multiple definition of `IRrecv::start(unsigned int)'
sketch/basic_commands.ino.cpp.o (symbol from plugin):(.text+0x0): first defined here
libraries/MideaIRWrapper/MidearIR.cpp.o (symbol from plugin): In function `irparams':
(.text+0x0): multiple definition of `IRrecv::initDecodedIRData()'
sketch/basic_commands.ino.cpp.o (symbol from plugin):(.text+0x0): first defined here
libraries/MideaIRWrapper/MidearIR.cpp.o (symbol from plugin): In function `irparams':
(.text+0x0): multiple definition of `IRrecv::available()'
sketch/basic_commands.ino.cpp.o (symbol from plugin):(.text+0x0): first defined here
libraries/MideaIRWrapper/MidearIR.cpp.o (symbol from plugin): In function `irparams':
(.text+0x0): multiple definition of `IRrecv::initBiphaselevel(unsigned char, unsigned int)'
sketch/basic_commands.ino.cpp.o (symbol from plugin):(.text+0x0): first defined here
libraries/MideaIRWrapper/MidearIR.cpp.o (symbol from plugin): In function `irparams':
(.text+0x0): multiple definition of `sBiphaseDecodeRawbuffOffset'
sketch/basic_commands.ino.cpp.o (symbol from plugin):(.text+0x0): first defined here
libraries/MideaIRWrapper/MidearIR.cpp.o (symbol from plugin): In function `irparams':
(.text+0x0): multiple definition of `sBiphaseTimeUnit'
sketch/basic_commands.ino.cpp.o (symbol from plugin):(.text+0x0): first defined here
libraries/MideaIRWrapper/MidearIR.cpp.o (symbol from plugin): In function `irparams':
(.text+0x0): multiple definition of `sUsedTimingIntervals'
sketch/basic_commands.ino.cpp.o (symbol from plugin):(.text+0x0): first defined here
libraries/MideaIRWrapper/MidearIR.cpp.o (symbol from plugin): In function `irparams':
(.text+0x0): multiple definition of `IRrecv::compare(unsigned int, unsigned int)'
sketch/basic_commands.ino.cpp.o (symbol from plugin):(.text+0x0): first defined here
libraries/MideaIRWrapper/MidearIR.cpp.o (symbol from plugin): In function `irparams':
(.text+0x0): multiple definition of `IRrecv::decodeHash()'
sketch/basic_commands.ino.cpp.o (symbol from plugin):(.text+0x0): first defined here
libraries/MideaIRWrapper/MidearIR.cpp.o (symbol from plugin): In function `irparams':
(.text+0x0): multiple definition of `IRrecv::decode()'
sketch/basic_commands.ino.cpp.o (symbol from plugin):(.text+0x0): first defined here
libraries/MideaIRWrapper/MidearIR.cpp.o (symbol from plugin): In function `irparams':
(.text+0x0): multiple definition of `IRrecv::read()'
sketch/basic_commands.ino.cpp.o (symbol from plugin):(.text+0x0): first defined here
libraries/MideaIRWrapper/MidearIR.cpp.o (symbol from plugin): In function `irparams':
(.text+0x0): multiple definition of `IRrecv::decodeHashOld(decode_results*)'
sketch/basic_commands.ino.cpp.o (symbol from plugin):(.text+0x0): first defined here
libraries/MideaIRWrapper/MidearIR.cpp.o (symbol from plugin): In function `irparams':
(.text+0x0): multiple definition of `matchTicks(unsigned int, unsigned int)'
sketch/basic_commands.ino.cpp.o (symbol from plugin):(.text+0x0): first defined here
libraries/MideaIRWrapper/MidearIR.cpp.o (symbol from plugin): In function `irparams':
(.text+0x0): multiple definition of `IRrecv::getBiphaselevel()'
sketch/basic_commands.ino.cpp.o (symbol from plugin):(.text+0x0): first defined here
libraries/MideaIRWrapper/MidearIR.cpp.o (symbol from plugin): In function `irparams':
(.text+0x0): multiple definition of `sCurrentTimingIntervals'
sketch/basic_commands.ino.cpp.o (symbol from plugin):(.text+0x0): first defined here
libraries/MideaIRWrapper/MidearIR.cpp.o (symbol from plugin): In function `irparams':
(.text+0x0): multiple definition of `MATCH(unsigned int, unsigned int)'
sketch/basic_commands.ino.cpp.o (symbol from plugin):(.text+0x0): first defined here
libraries/MideaIRWrapper/MidearIR.cpp.o (symbol from plugin): In function `irparams':
(.text+0x0): multiple definition of `matchMark(unsigned int, unsigned int)'
sketch/basic_commands.ino.cpp.o (symbol from plugin):(.text+0x0): first defined here
libraries/MideaIRWrapper/MidearIR.cpp.o (symbol from plugin): In function `irparams':
(.text+0x0): multiple definition of `MATCH_MARK(unsigned int, unsigned int)'
sketch/basic_commands.ino.cpp.o (symbol from plugin):(.text+0x0): first defined here
libraries/MideaIRWrapper/MidearIR.cpp.o (symbol from plugin): In function `irparams':
(.text+0x0): multiple definition of `matchSpace(unsigned int, unsigned int)'
sketch/basic_commands.ino.cpp.o (symbol from plugin):(.text+0x0): first defined here
libraries/MideaIRWrapper/MidearIR.cpp.o (symbol from plugin): In function `irparams':
(.text+0x0): multiple definition of `IRrecv::decodePulseWidthData(unsigned char, unsigned char, unsigned int, unsigned int, unsigned int, bool)'
sketch/basic_commands.ino.cpp.o (symbol from plugin):(.text+0x0): first defined here
libraries/MideaIRWrapper/MidearIR.cpp.o (symbol from plugin): In function `irparams':
(.text+0x0): multiple definition of `IRrecv::decodePulseDistanceData(unsigned char, unsigned char, unsigned int, unsigned int, unsigned int, bool)'
sketch/basic_commands.ino.cpp.o (symbol from plugin):(.text+0x0): first defined here
libraries/MideaIRWrapper/MidearIR.cpp.o (symbol from plugin): In function `irparams':
(.text+0x0): multiple definition of `MATCH_SPACE(unsigned int, unsigned int)'
sketch/basic_commands.ino.cpp.o (symbol from plugin):(.text+0x0): first defined here
libraries/MideaIRWrapper/MidearIR.cpp.o (symbol from plugin): In function `irparams':
(.text+0x0): multiple definition of `getMarkExcessMicros()'
sketch/basic_commands.ino.cpp.o (symbol from plugin):(.text+0x0): first defined here
libraries/MideaIRWrapper/MidearIR.cpp.o (symbol from plugin): In function `irparams':
(.text+0x0): multiple definition of `CheckForRecordGapsMicros(Print*, IRData*)'
sketch/basic_commands.ino.cpp.o (symbol from plugin):(.text+0x0): first defined here
libraries/MideaIRWrapper/MidearIR.cpp.o (symbol from plugin): In function `irparams':
(.text+0x0): multiple definition of `IRrecv::printIRResultMinimal(Print*)'
sketch/basic_commands.ino.cpp.o (symbol from plugin):(.text+0x0): first defined here
libraries/MideaIRWrapper/MidearIR.cpp.o (symbol from plugin): In function `irparams':
(.text+0x0): multiple definition of `IRrecv::printIRResultRawFormatted(Print*, bool)'
sketch/basic_commands.ino.cpp.o (symbol from plugin):(.text+0x0): first defined here
libraries/MideaIRWrapper/MidearIR.cpp.o (symbol from plugin): In function `irparams':
(.text+0x0): multiple definition of `IRrecv::compensateAndStoreIRResultInArray(unsigned char*)'
sketch/basic_commands.ino.cpp.o (symbol from plugin):(.text+0x0): first defined here
libraries/MideaIRWrapper/MidearIR.cpp.o (symbol from plugin): In function `irparams':
(.text+0x0): multiple definition of `IRrecv::printIRResultAsCVariables(Print*)'
"MideaIR.h" 对应多个库
 已使用： /Users/linquan/Documents/Arduino/libraries/MideaIRWrapper
sketch/basic_commands.ino.cpp.o (symbol from plugin):(.text+0x0): first defined here
 未使用：/Users/linquan/Documents/Arduino/libraries/ArduMideaWrapper-master
libraries/MideaIRWrapper/MidearIR.cpp.o (symbol from plugin): In function `irparams':
(.text+0x0): multiple definition of `getProtocolString(decode_type_t)'
sketch/basic_commands.ino.cpp.o (symbol from plugin):(.text+0x0): first defined here
libraries/MideaIRWrapper/MidearIR.cpp.o (symbol from plugin): In function `irparams':
(.text+0x0): multiple definition of `printIRResultShort(Print*, IRData*, unsigned int)'
sketch/basic_commands.ino.cpp.o (symbol from plugin):(.text+0x0): first defined here
libraries/MideaIRWrapper/MidearIR.cpp.o (symbol from plugin): In function `irparams':
(.text+0x0): multiple definition of `IRrecv::printIRResultShort(Print*)'
sketch/basic_commands.ino.cpp.o (symbol from plugin):(.text+0x0): first defined here
libraries/MideaIRWrapper/MidearIR.cpp.o (symbol from plugin): In function `irparams':
(.text+0x0): multiple definition of `IRrecv::compensateAndPrintIRResultAsCArray(Print*, bool)'
sketch/basic_commands.ino.cpp.o (symbol from plugin):(.text+0x0): first defined here
libraries/MideaIRWrapper/MidearIR.cpp.o (symbol from plugin): In function `irparams':
(.text+0x0): multiple definition of `__vector_8'
sketch/basic_commands.ino.cpp.o (symbol from plugin):(.text+0x0): first defined here
libraries/MideaIRWrapper/MidearIR.cpp.o (symbol from plugin): In function `irparams':
(.text+0x0): multiple definition of `IRrecv::decode(decode_results*)'
sketch/basic_commands.ino.cpp.o (symbol from plugin):(.text+0x0): first defined here
libraries/MideaIRWrapper/MidearIR.cpp.o (symbol from plugin): In function `irparams':
(.text+0x0): multiple definition of `IRsend::IRsend()'
sketch/basic_commands.ino.cpp.o (symbol from plugin):(.text+0x0): first defined here
libraries/MideaIRWrapper/MidearIR.cpp.o (symbol from plugin): In function `irparams':
(.text+0x0): multiple definition of `IRsend::IRsend()'
sketch/basic_commands.ino.cpp.o (symbol from plugin):(.text+0x0): first defined here
libraries/MideaIRWrapper/MidearIR.cpp.o (symbol from plugin): In function `irparams':
(.text+0x0): multiple definition of `IRsend::IRsend(unsigned char)'
sketch/basic_commands.ino.cpp.o (symbol from plugin):(.text+0x0): first defined here
libraries/MideaIRWrapper/MidearIR.cpp.o (symbol from plugin): In function `irparams':
(.text+0x0): multiple definition of `IRsend::IRsend(unsigned char)'
sketch/basic_commands.ino.cpp.o (symbol from plugin):(.text+0x0): first defined here
libraries/MideaIRWrapper/MidearIR.cpp.o (symbol from plugin): In function `irparams':
(.text+0x0): multiple definition of `IRsend::setSendPin(unsigned char)'
sketch/basic_commands.ino.cpp.o (symbol from plugin):(.text+0x0): first defined here
libraries/MideaIRWrapper/MidearIR.cpp.o (symbol from plugin): In function `irparams':
(.text+0x0): multiple definition of `IRsend::begin(unsigned char, bool, unsigned char)'
sketch/basic_commands.ino.cpp.o (symbol from plugin):(.text+0x0): first defined here
libraries/MideaIRWrapper/MidearIR.cpp.o (symbol from plugin): In function `irparams':
(.text+0x0): multiple definition of `IRsend::begin(bool, unsigned char)'
sketch/basic_commands.ino.cpp.o (symbol from plugin):(.text+0x0): first defined here
libraries/MideaIRWrapper/MidearIR.cpp.o (symbol from plugin): In function `irparams':
(.text+0x0): multiple definition of `IRsend::write(IRData*, unsigned char)'
sketch/basic_commands.ino.cpp.o (symbol from plugin):(.text+0x0): first defined here
libraries/MideaIRWrapper/MidearIR.cpp.o (symbol from plugin): In function `irparams':
(.text+0x0): multiple definition of `IRsend::mark(unsigned int)'
sketch/basic_commands.ino.cpp.o (symbol from plugin):(.text+0x0): first defined here
libraries/MideaIRWrapper/MidearIR.cpp.o (symbol from plugin): In function `irparams':
(.text+0x0): multiple definition of `IRsend::IRLedOff()'
sketch/basic_commands.ino.cpp.o (symbol from plugin):(.text+0x0): first defined here
libraries/MideaIRWrapper/MidearIR.cpp.o (symbol from plugin): In function `irparams':
(.text+0x0): multiple definition of `IRsend::customDelayMicroseconds(unsigned long)'
sketch/basic_commands.ino.cpp.o (symbol from plugin):(.text+0x0): first defined here
libraries/MideaIRWrapper/MidearIR.cpp.o (symbol from plugin): In function `irparams':
(.text+0x0): multiple definition of `IRsend::space(unsigned int)'
sketch/basic_commands.ino.cpp.o (symbol from plugin):(.text+0x0): first defined here
libraries/MideaIRWrapper/MidearIR.cpp.o (symbol from plugin): In function `irparams':
(.text+0x0): multiple definition of `IRsend::sendPulseDistanceWidthData(unsigned int, unsigned int, unsigned int, unsigned int, unsigned long, unsigned char, bool, bool)'
sketch/basic_commands.ino.cpp.o (symbol from plugin):(.text+0x0): first defined here
libraries/MideaIRWrapper/MidearIR.cpp.o (symbol from plugin): In function `irparams':
(.text+0x0): multiple definition of `IRsend::sendBiphaseData(unsigned int, unsigned long, unsigned char)'
sketch/basic_commands.ino.cpp.o (symbol from plugin):(.text+0x0): first defined here
libraries/MideaIRWrapper/MidearIR.cpp.o (symbol from plugin): In function `irparams':
(.text+0x0): multiple definition of `IRsend::enableIROut(unsigned char)'
sketch/basic_commands.ino.cpp.o (symbol from plugin):(.text+0x0): first defined here
libraries/MideaIRWrapper/MidearIR.cpp.o (symbol from plugin): In function `irparams':
(.text+0x0): multiple definition of `IRsend::sendRaw(unsigned int const*, unsigned char, unsigned char)'
sketch/basic_commands.ino.cpp.o (symbol from plugin):(.text+0x0): first defined here
libraries/MideaIRWrapper/MidearIR.cpp.o (symbol from plugin): In function `irparams':
(.text+0x0): multiple definition of `IRsend::sendRaw(unsigned char const*, unsigned char, unsigned char)'
sketch/basic_commands.ino.cpp.o (symbol from plugin):(.text+0x0): first defined here
libraries/MideaIRWrapper/MidearIR.cpp.o (symbol from plugin): In function `irparams':
(.text+0x0): multiple definition of `IRsend::sendRaw_P(unsigned int const*, unsigned char, unsigned char)'
sketch/basic_commands.ino.cpp.o (symbol from plugin):(.text+0x0): first defined here
libraries/MideaIRWrapper/MidearIR.cpp.o (symbol from plugin): In function `irparams':
(.text+0x0): multiple definition of `IRsend::sendRaw_P(unsigned char const*, unsigned char, unsigned char)'
sketch/basic_commands.ino.cpp.o (symbol from plugin):(.text+0x0): first defined here
libraries/MideaIRWrapper/MidearIR.cpp.o (symbol from plugin): In function `irparams':
(.text+0x0): multiple definition of `IRsend::getPulseCorrectionNanos()'
sketch/basic_commands.ino.cpp.o (symbol from plugin):(.text+0x0): first defined here
libraries/MideaIRWrapper/MidearIR.cpp.o (symbol from plugin): In function `irparams':
(.text+0x0): multiple definition of `IrSender'
sketch/basic_commands.ino.cpp.o (symbol from plugin):(.text+0x0): first defined here
collect2: error: ld returned 1 exit status
exit status 1

**Comment by md1024** [comment]
seeing this too. OSX 12.5.

**Comment by vanshksingh** [comment]
### This lib only supports IRremote 2.x.x so you will have to downgrade your IRremote library to 2.5.0 or 2.0.0 for it to work 

It fails to work on 2.8.1 on Attiny85 for pin 1 here atleast 



![Screenshot 2024-04-23 at 3 37 19 AM](https://github.com/WiserUFBA/ArduMideaWrapper/assets/114809624/24a83b9b-61c0-4c9b-970f-d66ac5cbae68)
